baseurl = "http://blog.adro.ml"
disablePathToLower = false
languageCode = "zh-cn"
title = "Adro's Blog"
theme = "hugo-octopress"

# Number of blog posts displayed in each page
paginate = 6

pygmentsuseclasses = false
pygmentsstyle = "solarized_dark"

# You need to install Solarized from https://github.com/john2x/solarized-pygment.git
# Octopress blog used Solarized_dark
# Options are solarized_dark (octopress), solarized_dark256 and default (solarized light)

# This will make the highlight shortcode and ``` do the same thing - otherwise they are treated differently and we do not want that
pygmentscodefences = true

# We can pass in pygments options here, it can also be added in the highlight shortcode
# pygmentsoptions = "linenos=true"

[permalinks]
post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

# Make tags and categories work
[indexes]
	tag = "tags"
	category = "categories"

# Menu
# Links are added to navigation in hugo-octopress/layouts/partials/navigation.html
# If navigationNewWindow is set in [params] to true then all links except root ("/") will open in a new window
# If navigationNewWindow does not exist or set to false then links will open in the same window
[[menu.main]]
	Name = "Blog"
	URL = "/"
	weight = -5

[[menu.main]]
	Name = "Categories"
	URL = "/categories"
	weight = -5

[[menu.main]]
	Name = "Tags"
	URL = "/tags"
	weight = -5

[[menu.main]]
	Name = "Google"
	URL = "https://www.google.com/"
	weight = -4

[[menu.main]]
	Name = "This theme on Github"
	URL = "https://www.github.com/parsiya/hugo-octopress"
	weight = -4


# Sidebar menus
# Enable with "sidebarMenuEnabled = true" in [params]
# Header text is "sidebarMenuHeader" in [params]
[[menu.sidebar]]
	Name = "Google"
	URL = "https://www.google.com"
	weight = 0

[[menu.sidebar]]
	Name = "Hugo"
	URL = "/categories/hugo/"
	weight = 1

[[menu.sidebar]]
	Name = "Homepage"
	URL = "/"
	weight = 2

[params]

	# --- Start sidebar options ---
	# Number of recent posts that will be shown in the sidebar - set to 0 or remove to hide this section
	sidebarRecentLimit = 10

	# Sidebar header - passed to markdownify so you can write markdown here
	sidebarHeader = "About Me"

	# Sidebar text also sipports markdown
	# New lines can be added with </br> or normal markdown (two spaces at the end of line or two new lines).
	# when adding two new lines, remember to remove the indentation otherwise the new line will be treated as a codeblock

	sidebarText = 'I am Adro Tan, master degree candidate at [Xidian University](http://www.xidian.edu.cn/).
	</br>
	</br>
    I am interested in embedded system, reverse engineering, Golang, CPP and game programming.
	</br>
	</br>
	This website is mostly for my own benefit to document my knowledge and a place to look things up. Hopefully it is useful for others.
    </br>
	</br>
    You can contact me via my email shamaoxiaogui@gmail.com or QQ 245203251
	'
	# Sidebar menu - if true will add a sidebar menu between sidebar text and recent posts
	sidebarMenuEnabled = true
	sidebarMenuHeader = "Collections"

	# sidebar links
	github = "https://github.com/shamaoxiaogui/"
	bitbucket = ""
	twitter = ""
	keybase = ""
	stackoverflow = ""
	linkedin = ""
	googleplus = ""
	youtube = ""
	facebook = ""

	# --- End sidebar options ---

	# If set to true, navigation menu links will open in a new window with the exception of links to root ("\")
	# If this item does not exist or set to false, then navigation menu links will open in the same window
	navigationNewWindow = true

	# If false, all of the post will appear on front page (and in pagination)
	truncate = true

	# Author's name (this will appear in metadata and under posts)
	author = "Adro Tan"

	# This text appears in the site header under website title
	subtitle = "小标题要长，这样才能显示出我们好像真的干了好多事情"

	# Used in the search engine
	searchEngineURL = "https://www.google.com/search"

	# Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so we will add it to index.html manually
	continueReadingText = "Would you like to know more?"

	# Google analytics code
	googleAnalytics = "UA-67880509-2"

	# Disqus shortcode
	# Disable comments for a specific post by adding "comments: false" in its frontmatter
	disqusShortname = "adro"

	rss = true  # switch to true to enable RSS icon link

	# Set to true to use a text label for RSS instead of an icon
	# This is overwritten by the `rss` setting
	textrss = false

	# Website's default description
	defaultDescription = ""

	# Populate this with your own search keywords - these will appear in the meta tags
	# defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

	# CSS override files
	# Paths should be relative to the `static` directory (either the website static directory or the theme one)
	# customCSS = ["css/custom.css","css/custom2.css"]

	# 404.html header and text -both support markdown
	notFoundHeader = "There's nothing here"

	notFoundText = 'Please either go back or use the navigation/sidebar menus.
	'

	# Set to true to hide ReadingTime on posts
	disableReadingTime = false

	# Set to true to disable downloading of remote Google fonts
	disableGoogleFonts = false

	# Generate taxonomy pages
	generateTaxonomyList = true

	# This is not needed unless alphabetical sort is needed
    sortTaxonomyAlphabetical = true


# Blackfriday is Hugo's markdown engine. Options are at: https://gohugo.io/overview/configuration/ (scroll down to "Configure Blackfriday rendering")
[blackfriday]
	hrefTargetBlank = true # open the external links in a new window
	fractions = false
